OPENAI_API_KEY = "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"
TAVILY_API_KEY = "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"
GITHUB_ACCESS_TOKEN = "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"